model: 
  num_frames: 3 # Must be matched with dataset.num_frmaes
  embed_dim: 64
    
train:
  save_path: "/mnt/home/20263312/dehazing/checkpoint" # Saving directory path
  save_interval: 20
  seed: 42
  epochs: 60
  loss_type: 'l1'
  smooth_weight: 0.005 # Not used in train_base
  prior_loss_type: 'l1' # Not used in train_base
  prior_weight: 0.2   # Not used in train_base
  prior_patch_size: 11  # Not used in train_base, odd number
  clip_grad: false
  max_grad: 1.0
  lr: 1e-4

  dataset:
    root_dir: "/mnt/home/20263312/data" # Dataset root directory path
    num_frames: 3 
    batch_size: 4
    num_workers: 4
    shuffle: true
    pin_memory: true
    drop_last: true
    persistent_workers: true
  
  transform:
    crop_size: 384